codecov:
  require_ci_to_pass: no
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 70%
        threshold: 5%
        informational: false
    
    patch:
      default:
        target: 80%
        threshold: 10%
        informational: false

comment:
  layout: "header, diff, files, footer"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

ignore:
  - "**/*.razor"  # Blazor components hard to test
  - "**/wwwroot/**"  # Static assets
  - "**/obj/**"
  - "**/bin/**"
  - "**/*Test*.cs"  # Test files
  - "**/*Tests.cs"
