name: Bug report
description: Report a problem in the app
title: "bug: "
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened? What did you expect?
      placeholder: Clear and concise description
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: List the steps to reproduce the issue
      placeholder: 1) … 2) … 3) …
    validations:
      required: true
  - type: textarea
    id: samples
    attributes:
      label: Sample files
      description: Attach example mod ZIPs or `.hhh` bundles if possible
  - type: input
    id: browser
    attributes:
      label: Browser & version
      placeholder: Chrome 121, Firefox 120, etc.
  - type: input
    id: os
    attributes:
      label: Operating system
      placeholder: Windows 11 / macOS 14 / Ubuntu 24.04
  - type: checkboxes
    id: regress
    attributes:
      label: Regression?
      options:
        - label: I tested on the latest `main`
        - label: I tested with a fresh browser profile