name: Bug Report
description: File a bug report
labels: [bug]
body:
  - type: input
    id: summary
    attributes:
      label: Summary
      description: Short description of the bug
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to Reproduce
      description: Step-by-step reproduction
      placeholder: |
        1. Go to ...
        2. Click ...
        3. See error ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs / Console Output
      render: shell
  - type: input
    id: fixture
    attributes:
      label: Fixture ID (if parser-related)
      description: e.g., synthetic-minimal-v1.hhh
  - type: input
    id: env
    attributes:
      label: Environment
      description: OS, browser, Node version
  - type: dropdown
    id: area
    attributes:
      label: Affected Area
      options:
        - parser
        - worker
        - web
        - docs
        - ci
        - other
    validations:
      required: true
