name: Feature request
description: Suggest an idea for this project
title: "feat: "
labels: [enhancement]
body:
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: What do you want to happen?
      placeholder: Describe the feature
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this useful? What problem does it solve?
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: Define scope and expected outcomes
      placeholder: Bullet points of outcomes
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
  - type: checkboxes
    id: checks
    attributes:
      label: Checks
      options:
        - label: I’m willing to help implement this
        - label: This aligns with Level 2 UnityFS parsing