name: Task / Chore
description: Small task (CI, docs, infra, cleanup)
labels: [task]
body:
  - type: input
    id: summary
    attributes:
      label: Summary
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Details
  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - parser
        - worker
        - web
        - docs
        - ci
        - other
    validations:
      required: true
